### ISSUE TITLE
Corrupted image `images/next_move.png`

### ISSUE THREAD

**Issue by graipher** [fudgenuggets1/hax_free_pokemon#2]
The file `images/next_move.png` is corrupted, so I can't even open it normally.

**Comment by graipher** [comment]
While it looks fine in the raw view here on github, when downloading it, the GNOME image viewer complains:
Fatal error reading PNG image file: Decompression error in IDAT

And Python complains:

```
libpng error: IDAT: invalid distance too far back
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from interaction import interaction
  File "/home/andreas/Downloads/hax_free_pokemon-master/interaction.py", line 3, in <module>
    from game import Game
  File "/home/andreas/Downloads/hax_free_pokemon-master/game.py", line 9, in <module>
    class Game():
  File "/home/andreas/Downloads/hax_free_pokemon-master/game.py", line 63, in Game
    next_move_text = pygame.image.load('images/next_move.png')
pygame.error: Error reading the PNG file.
```
